In [1]:
#import required libraries
import pandas as pd
import numpy as np
from IPython.display import Markdown as md,display
import time
import datetime

In [2]:
data = pd.read_csv('data/finalTrain.csv')
data

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weather_conditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken (min)
0,0xcdcd,DEHRES17DEL01,36.0,4.2,30.327968,78.046106,30.397968,78.116106,12-02-2022,21:55,22:10,Fog,Jam,2,Snack,motorcycle,3.0,No,Metropolitian,46
1,0xd987,KOCRES16DEL01,21.0,4.7,10.003064,76.307589,10.043064,76.347589,13-02-2022,14:55,15:05,Stormy,High,1,Meal,motorcycle,1.0,No,Metropolitian,23
2,0x2784,PUNERES13DEL03,23.0,4.7,18.562450,73.916619,18.652450,74.006619,04-03-2022,17:30,17:40,Sandstorms,Medium,1,Drinks,scooter,1.0,No,Metropolitian,21
3,0xc8b6,LUDHRES15DEL02,34.0,4.3,30.899584,75.809346,30.919584,75.829346,13-02-2022,09:20,09:30,Sandstorms,Low,0,Buffet,motorcycle,0.0,No,Metropolitian,20
4,0xdb64,KNPRES14DEL02,24.0,4.7,26.463504,80.372929,26.593504,80.502929,14-02-2022,19:50,20:05,Fog,Jam,1,Snack,scooter,1.0,No,Metropolitian,41
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45579,0x7c09,JAPRES04DEL01,30.0,4.8,26.902328,75.794257,26.912328,75.804257,24-03-2022,11:35,11:45,Windy,High,1,Meal,motorcycle,0.0,No,Metropolitian,32
45580,0xd641,AGRRES16DEL01,21.0,4.6,0.000000,0.000000,0.070000,0.070000,16-02-2022,19:55,20:10,Windy,Jam,0,Buffet,motorcycle,1.0,No,Metropolitian,36
45581,0x4f8d,CHENRES08DEL03,30.0,4.9,13.022394,80.242439,13.052394,80.272439,11-03-2022,23:50,24:05:00,Cloudy,Low,1,Drinks,scooter,0.0,No,Metropolitian,16
45582,0x5eee,COIMBRES11DEL01,20.0,4.7,11.001753,76.986241,11.041753,77.026241,07-03-2022,13:35,13:40,Cloudy,High,0,Snack,motorcycle,1.0,No,Metropolitian,26
45583,0x5fb2,RANCHIRES09DEL02,23.0,4.9,23.351058,85.325731,23.431058,85.405731,02-03-2022,17:10,17:15,Fog,Medium,2,Snack,scooter,1.0,No,Metropolitian,36

In [3]:
dummy = data[~data.isna().any(axis=1)]

In [4]:
dummy

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weather_conditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken (min)
0,0xcdcd,DEHRES17DEL01,36.0,4.2,30.327968,78.046106,30.397968,78.116106,12-02-2022,21:55,22:10,Fog,Jam,2,Snack,motorcycle,3.0,No,Metropolitian,46
1,0xd987,KOCRES16DEL01,21.0,4.7,10.003064,76.307589,10.043064,76.347589,13-02-2022,14:55,15:05,Stormy,High,1,Meal,motorcycle,1.0,No,Metropolitian,23
2,0x2784,PUNERES13DEL03,23.0,4.7,18.562450,73.916619,18.652450,74.006619,04-03-2022,17:30,17:40,Sandstorms,Medium,1,Drinks,scooter,1.0,No,Metropolitian,21
3,0xc8b6,LUDHRES15DEL02,34.0,4.3,30.899584,75.809346,30.919584,75.829346,13-02-2022,09:20,09:30,Sandstorms,Low,0,Buffet,motorcycle,0.0,No,Metropolitian,20
4,0xdb64,KNPRES14DEL02,24.0,4.7,26.463504,80.372929,26.593504,80.502929,14-02-2022,19:50,20:05,Fog,Jam,1,Snack,scooter,1.0,No,Metropolitian,41
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45579,0x7c09,JAPRES04DEL01,30.0,4.8,26.902328,75.794257,26.912328,75.804257,24-03-2022,11:35,11:45,Windy,High,1,Meal,motorcycle,0.0,No,Metropolitian,32
45580,0xd641,AGRRES16DEL01,21.0,4.6,0.000000,0.000000,0.070000,0.070000,16-02-2022,19:55,20:10,Windy,Jam,0,Buffet,motorcycle,1.0,No,Metropolitian,36
45581,0x4f8d,CHENRES08DEL03,30.0,4.9,13.022394,80.242439,13.052394,80.272439,11-03-2022,23:50,24:05:00,Cloudy,Low,1,Drinks,scooter,0.0,No,Metropolitian,16
45582,0x5eee,COIMBRES11DEL01,20.0,4.7,11.001753,76.986241,11.041753,77.026241,07-03-2022,13:35,13:40,Cloudy,High,0,Snack,motorcycle,1.0,No,Metropolitian,26
45583,0x5fb2,RANCHIRES09DEL02,23.0,4.9,23.351058,85.325731,23.431058,85.405731,02-03-2022,17:10,17:15,Fog,Medium,2,Snack,scooter,1.0,No,Metropolitian,36

In [5]:
dummy[(~dummy.Time_Orderd.str.contains(r'[0-9]{2}:[0-9]{2}',na=False)) | (~dummy.Time_Order_picked.str.contains(r'[0-9]{2}:[0-9]{2}',na=False))]

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weather_conditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken (min)
28,0x6531,SURRES08DEL01,20.0,4.8,21.173343,72.792731,21.183343,72.802731,30-03-2022,0.458333333,11:10,Sandstorms,Low,2,Meal,scooter,1.0,No,Metropolitian,19
31,0x9b18,BANGRES17DEL01,22.0,4.8,12.972532,77.608179,13.042532,77.678179,18-03-2022,0.958333333,23:10,Fog,Low,1,Snack,motorcycle,1.0,No,Metropolitian,28
36,0xc644,KOLRES16DEL02,37.0,4.9,22.539129,88.365507,22.559129,88.385507,13-02-2022,10:55,0.458333333,Fog,Low,1,Snack,scooter,1.0,No,Urban,16
38,0x63b6,BANGRES05DEL03,27.0,4.9,12.970324,77.645748,13.030324,77.705748,19-03-2022,0.791666667,19:15,Windy,Medium,1,Drinks,scooter,1.0,No,Metropolitian,25
46,0x272d,COIMBRES07DEL03,24.0,4.7,10.961850,76.971082,11.051850,77.061082,10-03-2022,17:55,0.75,Sunny,Medium,0,Buffet,motorcycle,0.0,No,Urban,19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45544,0x46b6,PUNERES03DEL01,36.0,4.9,18.554382,73.798206,18.594382,73.838206,26-03-2022,0.541666667,13:10,Windy,High,2,Drinks,scooter,0.0,No,Metropolitian,28
45545,0x6607,COIMBRES16DEL02,26.0,4.2,11.010375,76.952950,11.030375,76.972950,01-04-2022,0.416666667,10:10,Windy,Low,0,Drinks,motorcycle,1.0,No,Urban,18
45566,0x91d5,HYDRES03DEL03,34.0,4.9,17.422819,78.449578,17.482819,78.509578,24-03-2022,21:45,0.916666667,Stormy,Jam,1,Meal,motorcycle,1.0,No,Metropolitian,28
45573,0x59ae,PUNERES13DEL02,30.0,4.6,18.562450,73.916619,18.582450,73.936619,01-04-2022,0.375,09:15,Cloudy,Low,0,Meal,motorcycle,0.0,No,Metropolitian,20
45577,0x4e21,BANGRES16DEL03,28.0,4.9,13.029198,77.570997,13.059198,77.600997,30-03-2022,21:55,0.916666667,Sandstorms,Jam,1,Meal,scooter,1.0,No,Metropolitian,29

In [6]:
d2 = dummy[~((~dummy.Time_Orderd.str.contains(r'[0-9]{2}:[0-9]{2}',na=False)) | (~dummy.Time_Order_picked.str.contains(r'[0-9]{2}:[0-9]{2}',na=False)))]

In [7]:
41359-7576

33783

In [8]:
d2['Time_Orderd'].unique()

array(['21:55', '14:55', '17:30', '09:20', '19:50', '20:25', '20:30',
       '21:15', '20:20', '22:30', '08:15', '19:30', '12:25', '18:35',
       '20:35', '23:20', '21:20', '23:35', '22:35', '23:25', '13:35',
       '21:35', '18:55', '14:15', '09:45', '08:40', '17:25', '19:45',
       '19:10', '21:40', '16:45', '11:30', '15:10', '22:45', '22:10',
       '20:45', '22:50', '20:15', '22:25', '22:40', '23:50', '15:25',
       '10:20', '10:40', '15:55', '20:10', '12:10', '15:30', '10:35',
       '21:10', '12:35', '23:40', '18:15', '18:20', '11:45', '12:45',
       '23:30', '10:50', '21:25', '10:10', '17:50', '22:20', '12:40',
       '23:55', '10:25', '10:55', '23:45', '22:15', '23:10', '18:25',
       '20:50', '18:45', '14:20', '10:15', '08:50', '16:35', '08:30',
       '19:55', '21:45', '18:10', '12:20', '12:50', '09:10', '12:30',
       '17:10', '19:15', '20:40', '17:20', '18:30', '13:10', '17:55',
       '19:35', '09:50', '17:45', '10:30', '09:40', '15:35', '14:50',
       '22:55', '17:15', '21:30', '18:40', '11:10', '13:50', '21:50',
       '11:50', '20:55', '08:25', '11:20', '11:55', '09:30', '08:20',
       '08:10', '11:40', '23:15', '19:20', '13:30', '12:15', '08:45',
       '09:25', '11:35', '17:35', '17:40', '14:40', '18:50', '11:25',
       '19:40', '14:25', '16:10', '19:25', '13:40', '09:35', '08:35',
       '11:15', '16:15', '09:15', '13:20', '15:50', '15:20', '16:20',
       '14:30', '15:45', '16:55', '12:55', '10:45', '13:25', '09:55',
       '15:15', '13:15', '15:40', '16:25', '14:10', '13:45', '13:55',
       '16:50', '16:40', '14:35', '08:55', '16:30', '14:45'], dtype=object)

In [9]:
d2['Time_Orderd'] = pd.to_datetime(d2['Order_Date'] + ' ' + d2['Time_Orderd'], format='%d-%m-%Y %H:%M')
d2

C:\Users\ramag\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weather_conditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken (min)
0,0xcdcd,DEHRES17DEL01,36.0,4.2,30.327968,78.046106,30.397968,78.116106,12-02-2022,2022-02-12 21:55:00,22:10,Fog,Jam,2,Snack,motorcycle,3.0,No,Metropolitian,46
1,0xd987,KOCRES16DEL01,21.0,4.7,10.003064,76.307589,10.043064,76.347589,13-02-2022,2022-02-13 14:55:00,15:05,Stormy,High,1,Meal,motorcycle,1.0,No,Metropolitian,23
2,0x2784,PUNERES13DEL03,23.0,4.7,18.562450,73.916619,18.652450,74.006619,04-03-2022,2022-03-04 17:30:00,17:40,Sandstorms,Medium,1,Drinks,scooter,1.0,No,Metropolitian,21
3,0xc8b6,LUDHRES15DEL02,34.0,4.3,30.899584,75.809346,30.919584,75.829346,13-02-2022,2022-02-13 09:20:00,09:30,Sandstorms,Low,0,Buffet,motorcycle,0.0,No,Metropolitian,20
4,0xdb64,KNPRES14DEL02,24.0,4.7,26.463504,80.372929,26.593504,80.502929,14-02-2022,2022-02-14 19:50:00,20:05,Fog,Jam,1,Snack,scooter,1.0,No,Metropolitian,41
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45579,0x7c09,JAPRES04DEL01,30.0,4.8,26.902328,75.794257,26.912328,75.804257,24-03-2022,2022-03-24 11:35:00,11:45,Windy,High,1,Meal,motorcycle,0.0,No,Metropolitian,32
45580,0xd641,AGRRES16DEL01,21.0,4.6,0.000000,0.000000,0.070000,0.070000,16-02-2022,2022-02-16 19:55:00,20:10,Windy,Jam,0,Buffet,motorcycle,1.0,No,Metropolitian,36
45581,0x4f8d,CHENRES08DEL03,30.0,4.9,13.022394,80.242439,13.052394,80.272439,11-03-2022,2022-03-11 23:50:00,24:05:00,Cloudy,Low,1,Drinks,scooter,0.0,No,Metropolitian,16
45582,0x5eee,COIMBRES11DEL01,20.0,4.7,11.001753,76.986241,11.041753,77.026241,07-03-2022,2022-03-07 13:35:00,13:40,Cloudy,High,0,Snack,motorcycle,1.0,No,Metropolitian,26
45583,0x5fb2,RANCHIRES09DEL02,23.0,4.9,23.351058,85.325731,23.431058,85.405731,02-03-2022,2022-03-02 17:10:00,17:15,Fog,Medium,2,Snack,scooter,1.0,No,Metropolitian,36

In [10]:
d2.Time_Order_picked = d2.Time_Order_picked.str.replace('24','00')

C:\Users\ramag\anaconda3\lib\site-packages\pandas\core\generic.py:5303: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value

In [11]:
d2.Time_Order_picked.str.contains('24').sum()

0

In [19]:
d2['Time_Order_picked'] = d2['Time_Order_picked'].str[0:5]

C:\Users\ramag\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [ ]:
d2['Time_Order_picked'] = pd.to_datetime(d2['Order_Date'] + ' ' + d2['Time_Order_picked'])
d2

In [ ]:
(time.mktime((pd.to_datetime(d2['Time_Order_picked'].iloc[0])).timetuple()) - time.mktime((pd.to_datetime(d2['Time_Orderd'].iloc[0])).timetuple()))/60

In [13]:
d2['Time_Order_picked'].unique()

array(['22:10', '15:05', '17:40', '09:30', '20:05', '20:35', '15:10',
       '20:40', '21:30', '20:25', '22:45', '08:30', '19:45', '12:30',
       '18:50', '23:30', '21:35', '23:45', '22:50', '22:40', '23:35',
       '13:40', '21:45', '19:10', '14:25', '09:55', '08:55', '17:30',
       '19:50', '19:25', '16:55', '11:40', '15:15', '22:55', '22:25',
       '20:55', '23:05', '20:50', '20:20', '22:35', '23:55', '15:40',
       '10:30', '10:50', '16:05', '20:15', '12:15', '15:45', '22:15',
       '10:45', '00:05:00', '21:25', '12:45', '18:20', '18:25', '11:50',
       '12:50', '10:55', '21:40', '10:20', '17:55', '23:50', '12:55',
       '00:10:00', '10:40', '11:10', '20:45', '23:15', '18:35', '22:20',
       '21:05', '21:20', '14:35', '10:25', '16:50', '08:40', '23:40',
       '21:50', '10:35', '09:25', '17:20', '19:30', '17:25', '20:10',
       '17:35', '19:15', '13:20', '18:05', '19:20', '10:05', '21:55',
       '19:40', '18:10', '09:50', '15:50', '18:30', '18:15', '21:15',
       '15:30', '22:30', '15:20', '23:20', '11:25', '13:55', '18:45',
       '22:05', '11:55', '18:55', '21:10', '18:40', '09:45', '17:15',
       '12:05', '11:15', '19:35', '08:25', '12:40', '12:25', '08:20',
       '23:25', '16:10', '17:50', '13:45', '08:15', '08:45', '09:40',
       '20:30', '08:50', '14:45', '17:45', '08:35', '19:55', '11:35',
       '11:20', '14:30', '19:05', '16:15', '11:30', '16:25', '13:35',
       '15:55', '15:35', '09:05', '09:15', '17:05', '13:05', '23:10',
       '10:10', '11:45', '09:35', '16:20', '16:30', '16:45', '09:20',
       '13:25', '12:10', '16:35', '16:40', '14:05', '13:30', '14:40',
       '10:15', '12:20', '13:50', '17:10', '14:20', '12:35', '14:10',
       '15:25', '13:10', '14:15', '11:05', '14:55', '09:10', '14:50',
       '13:15'], dtype=object)

In [17]:
extra = d2.Time_Order_picked.str.contains(r'[0-9]{2}:[0-9]{2}:[0-9]{2}')

d2[extra]['Time_Order_picked'].unique()

array(['00:05:00', '00:10:00'], dtype=object)

In [ ]:
d2.Time_Order_picked.unique()

d2.Time_Order_picked.str.contains(r'[0-9]{2}:[0-9]{2}:[0-9]{2}').sum()

In [ ]:
diff = pd.to_datetime(d2['Time_Order_picked']) - pd.to_datetime(d2['Time_Orderd'])
diff.dt.seconds/60

In [ ]:
pd.to_datetime(d2['Time_Order_picked'])

In [ ]:
diff = (pd.to_datetime(d2['Time_Order_picked']) - pd.to_datetime(d2['Time_Orderd'])).dt.seconds/60

In [ ]:
d2.insert(loc=11, column='Prep_time', value=diff)

In [ ]:
d2

In [ ]:
len(d2.columns)

In [ ]:
d2.info()

In [ ]:
def haversine_np(lon1, lat1, lon2, lat2):
    """
    Calculate the great circle distance between two points
    on the earth (specified in decimal degrees)

    All args must be of equal length.    

    """
    lon1, lat1, lon2, lat2 = map(np.radians, [lon1, lat1, lon2, lat2])

    dlon = lon2 - lon1
    dlat = lat2 - lat1

    a = np.sin(dlat/2.0)**2 + np.cos(lat1) * np.cos(lat2) * np.sin(dlon/2.0)**2

    c = 2 * np.arcsin(np.sqrt(a))
    km = 6378 * c
    return km

In [ ]:
import numpy as np
import pandas
lon1, lon2, lat1, lat2 = np.random.randn(4, 1000000)
df = pandas.DataFrame(data={'lon1':lon1,'lon2':lon2,'lat1':lat1,'lat2':lat2})
km = haversine_np(df['lon1'],df['lat1'],df['lon2'],df['lat2'])

In [ ]:
df

In [ ]:
distance_km = haversine_np(d2['Restaurant_longitude'],d2['Restaurant_latitude'],d2['Delivery_location_longitude'],d2['Delivery_location_latitude'])

In [ ]:
d2.insert(loc=20,column='Distance',value=distance_km.round(2))

In [ ]:
d2.head()

In [ ]:
distance_km.round(2)

In [ ]:
d2.info()

In [ ]:
d2.Delivery_person_Ratings.unique()

In [ ]:
d2.columns = d2.columns.str.replace(' ','').str.replace("(",'_').str.replace(")",'')

In [ ]:
d2.columns

In [ ]:
d2.head()

In [ ]:
d2.info()

In [ ]:
d2.columns

In [ ]:
d2.Vehicle_condition.value_counts()

In [ ]:
d2.Weather_conditions.unique() #Nominal

In [ ]:
d2.Type_of_order.unique() #Nominal

In [ ]:
d2.Type_of_vehicle.unique() #N0minal

In [ ]:
d2.Festival.unique() #Nominal

In [ ]:
d2.City.unique() #nominal

In [ ]:
d2.multiple_deliveries.unique() #Ordinal

In [ ]:
d2.Road_traffic_density.unique() #ordinal

In [ ]:
d2.Vehicle_condition.unique() #Ordinal

In [ ]:
d2.info()

In [ ]:

# example of a ordinal encoding
from numpy import asarray
from sklearn.preprocessing import OrdinalEncoder
# define data
data = asarray([['red'], ['green'], ['blue']])
print(data)
# define ordinal encoding
encoder = OrdinalEncoder(categories=[''])
# transform data
result = encoder.fit_transform(data)
print(result)

In [ ]:
d2.to_csv('eda_cleaned.csv',index=False)